title: My First New Website

description: >
  This website is for class today 3/31/25

author:
  name: Paul Alexander
  email: palexand3042@gmail.com

nav_pages:
  - about.md
  - contact.md

max-width: 1600px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
